# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-05-01 05:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import micropub.models
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('file', models.FileField(upload_to=micropub.models.upload_to)),
            ],
            options={
                'verbose_name_plural': 'media',
            },
        ),
    ]
