# Generated by Django 4.0.3 on 2022-05-03 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micropub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indieauth',
            name='state',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
