# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-09-24 00:17
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('micropub', '0004_auto_20230924_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='extra',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_at',
            field=model_utils.fields.MonitorField(blank=True, default=None, monitor='status', null=True, when=set(['published'])),
        ),
    ]
