# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-08-28 05:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('micropub', '0005_post_syndication_targets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='syndicate_to',
        ),
    ]
