# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-09-24 00:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('micropub', '0006_post_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='timezone',
        ),
    ]
