# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-08-28 05:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('micropub', '0007_auto_20230828_0554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='syndication_to',
            new_name='syndicate_to',
        ),
    ]
