# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-03-07 05:51
from __future__ import unicode_literals

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('micropub', '0012_auto_20240307_0536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_at',
            field=model_utils.fields.MonitorField(blank=True, default=None, monitor='status', null=True, unique=True, when=set(['published'])),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=model_utils.fields.MonitorField(blank=True, default=None, monitor='status', null=True, unique=True, when=set(['updated'])),
        ),
    ]
