# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-04-27 21:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('micropub', '0014_auto_20240323_0126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='syndication',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='post',
            name='syndicate_to',
        ),
        migrations.DeleteModel(
            name='Syndication',
        ),
        migrations.DeleteModel(
            name='SyndicationTarget',
        ),
    ]
