# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-06-13 02:46
from __future__ import unicode_literals

from django.db import migrations, models
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('micropub', '0016_auto_20240511_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='content',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='media_type',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='audio', max_length=100, no_check_for_status=True),
        ),
        migrations.AddField(
            model_name='media',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
