# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-08-10 22:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('micropub', '0018_auto_20240613_0246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='extra',
        ),
    ]
