# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-08-28 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micropub', '0004_syndicationtarget'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='syndication_targets',
            field=models.ManyToManyField(to='micropub.SyndicationTarget'),
        ),
    ]
