# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-09-24 00:20
from __future__ import unicode_literals

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('micropub', '0005_auto_20230924_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='updated_at',
            field=model_utils.fields.MonitorField(blank=True, default=None, monitor='status', null=True, when=set(['updated'])),
        ),
    ]
