# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-09-27 03:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micropub', '0008_auto_20230828_0555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='syndicate_to',
            field=models.ManyToManyField(blank=True, to='micropub.SyndicationTarget'),
        ),
    ]
