# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-09-27 16:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('micropub', '0009_auto_20230927_0324'),
        ('micropub', '0007_remove_post_timezone'),
    ]

    operations = [
    ]
