# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-03-07 05:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('micropub', '0011_auto_20230929_0517'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='post',
            unique_together=set([('content', 'published_at')]),
        ),
    ]
