# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-03-23 01:26
from __future__ import unicode_literals

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('micropub', '0013_auto_20240307_0551'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('article', 'article'), ('bookmark', 'bookmark'), ('favorite', 'favorite'), ('note', 'note'), ('reply', 'reply'), ('repost', 'repost'), ('rsvp', 'rsvp'), ('photo', 'photo')], default='note', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='post',
            unique_together=set([('content', 'published_at'), ('url', 'published_at')]),
        ),
    ]
