# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-05-11 20:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('micropub', '0015_auto_20240427_2112'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyndicationTarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uid', models.URLField(max_length=2000)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='post',
            name='syndicate_to',
            field=models.ManyToManyField(blank=True, to='micropub.SyndicationTarget'),
        ),
    ]
