# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-06-13 02:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('micropub', '0017_auto_20240613_0246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='content',
        ),
        migrations.RemoveField(
            model_name='media',
            name='media_type',
        ),
        migrations.RemoveField(
            model_name='media',
            name='name',
        ),
    ]
