# Generated by Django 4.0.4 on 2022-05-08 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micropub', '0002_alter_indieauth_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indieauth',
            name='code',
            field=models.TextField(blank=True),
        ),
    ]
