# Generated by Django 4.0.4 on 2022-05-28 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('micropub', '0003_alter_indieauth_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IndieAuth',
        ),
    ]
